{
  config,
  pkgs,
  lib,
  ...
}:
{
  nixpkgs.config.allowUnfree = true;
  imports = [
    ./antares-agent.nix
    ./configuration.nix
    ./gitsync.nix
    ./monitor.nix
    ./rpc-client.nix
    ./nix.nix
    ./packages.nix
    ../modules/nixos/runners.nix
    ./ssh-probe.nix
    ./git-server.nix
    ./user.nix
    ../modules/proxy.nix
    ./xray.nix
    ./napcat.nix
    ./qq.nix
    ./qq-credentials.nix
    ./qq-relay.nix
    ./qq-codex-agent.nix
  ]
  ++ [
    ../common/agenix.nix
    ../common/env.nix
    ../common/gnupg.nix
    ../common/nix.nix
    ../common/rabbitmq.nix
    ../common/time.nix
    ../common/zsh.nix
    ../common/nix-zshell.nix
  ];
}
