{
  config,
  pkgs,
  lib,
  ...
}:
{
  nixpkgs.config.allowUnfree = true;
  imports = [
    ../modules/proxy.nix
    ./xray.nix
    ./autostart.nix
    ./wait-online.nix
    ./audio.nix
    ./bluetooth.nix
    ./configuration.nix
    ./display.nix
    ./wallpaper.nix
    ./fcitx5.nix
    ./github-auth.nix
    ./git-sign-unlock.nix
    ./fonts.nix
    ./mcp-nixos.nix
    ./rpc-client.nix
    ./monitor.nix
    ./network.nix
    ./nix.nix
    ./nvidia.nix
    ./openlist.nix
    ./packages.nix
    ./qq.nix
    ./rust.nix
    ./samba.nix
    ./ssh.nix
    ./steam.nix
    ./user.nix
    ./ydotool.nix
  ]
  ++ [
    ../common/agenix.nix
    ../common/git-sign.nix
    ../common/gnupg.nix
    ../common/nix.nix
    ../common/nix-zshell.nix
    ../common/rabbitmq.nix
    ../common/time.nix
    ../common/zsh.nix
  ];
}
