name: "Flake Update & Build (RPi5)"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 21 * * *'  # 5:00 AM China Standard Time (UTC+8)

permissions:
  contents: write

jobs:
  build:
    runs-on: [self-hosted, Linux, ARM64]
    steps:
    - name: Checkout
      uses: actions/checkout@v6

    - name: Configure git
      run: |
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git config --global pull.rebase false

    - name: Setup cachix
      uses: cachix/cachix-action@v17
      with:
        name: antares0982
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
        skipAddingSubstituter: true

    - name: Nix flake update
      run: |
        nix flake update --commit-lock-file

    - name: Nix build (rpi5)
      run: |
        nix build -L .#nixosConfigurations.rpi5.config.system.build.toplevel --show-trace
